name: Release Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64]

    continue-on-error: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21

    - name: Build binary
      run: |
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o RobTycoon-${{ matrix.os }}-${{ matrix.arch }} main.go

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: RobTycoon-*
        token: ${{ secrets.GITHUB_TOKEN }}